feat: Lazyload for entities  Resolve: feat/PP-36
QoreCode/party-payments-server pull request #3
Opened 2023-07-26 17:38 UTC by vladokrushko

2023-07-30 20:04 UTC, QoreCode requested changes

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/ExcludeModification.php
> +#[ApiFilter(EntityFilter::class, properties: ['uid' => 'exact', 'paymentUid' => 'exact', 'userUid' => 'exact'])]
### 🤔 Question: Do we really need filter by `userUid`?

I don't see the case when we need it. Morover if we need it here, we will have to add it to `calculationModification`

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/CalculationModification.php
>  class CalculationModification
### ❗ Issue: Pls add comment field here

The `comment` field isn't requred, but should have text (or varchar) format. Btw... will u return `null` for no-set comment?)

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/MemberPayedFor.php
> +#[ApiFilter(EntityFilter::class, properties: ['uid' => 'exact', 'memberUid' => 'exact', 'payedForUserUid' => 'exact'])]
### 🤔 Question: Do we really need filter by payedForUserUid?

I don't see the case when we need it.

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/MemberPayedFor.php
> +    public function setPayedForUserUid(?User $payedForUserUid): static
### 🤓 Nitpick: Bad name or data

Is it a string property `userUid`? Or this func should be named as `setPayedForUser`?

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/PartyEvent.php
> +#[ApiFilter(EntityFilter::class, properties: ['uid' => 'exact', 'name' => 'partial', 'date' => 'exact'])]
### ☝ Suggestion: I think we should be able to set 'from' and 'to' range for date field or remove this filter at all

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/Payment.php
> +    'date'     => 'exact',
### ☝ Suggestion: Same as for `PartyEvent` entity :)

But... I believe we don't need this filter here at all)

2023-07-30 20:04 UTC, QoreCode commented on src/Entity/UserCalculationModification.php
> +#[ApiFilter(EntityFilter::class, properties: [
### 🤔 Question: Do we need to have it in api?

I think this is a tech table for relations. We don't need this info on the client :)

2023-07-30 20:04 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +        $this->identifiersExtractor = $identifiersExtractor;
### 🤓 Nitpick: it seems this isn't using anywhere )

2023-07-30 20:04 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +    protected function filterProperty(
### 🤓 Nitpick: Is it possible to reduce vars count here?

The big number of props past to func are indicate about bad func design.

2023-07-30 20:04 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +        $value,
### 🤓 Nitpick: No type for `$value`?

At 102 line u a marking this prop as array, so... maybe u should mark it as array here?

2023-07-30 20:04 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +        }
### ❗ Issue: Remove or use it)

The `$strategy` var is never used.

2023-07-30 20:04 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +        if (!$strategy || self::STRATEGY_EXACT === $strategy) {
### ☝ Suggestion: set `self::STRATEGY_EXACT` as default

U ca set `self::STRATEGY_EXACT` to avoid checking for empty `$strategy`

2023-07-30 20:04 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +    protected function filterProperty(
### 🤓 Nitpick: Something seems to be wrong with this func

Maybe it coz of me and it's ok for php, but it looks like very imperative-style hardcoded func. Can we have a call to try refactor it?)

2023-07-31 11:39 UTC, vladokrushko commented on src/Entity/CalculationModification.php
>  class CalculationModification
by default, if the value is null, the field would not be returned

2023-07-31 11:54 UTC, vladokrushko commented on src/Entity/Payment.php
> +    'date'     => 'exact',
right, we need only filter by `eventUid` at this point

2023-07-31 11:57 UTC, vladokrushko commented on src/Entity/PartyEvent.php
> +#[ApiFilter(EntityFilter::class, properties: ['uid' => 'exact', 'name' => 'partial', 'date' => 'exact'])]
date filter temporarily removed, would be added as the "range" filter when it would be necessary

2023-07-31 19:44 UTC, QoreCode commented on src/Entity/MemberPayedFor.php
> +#[ApiFilter(EntityFilter::class, properties: ['uid' => 'exact', 'memberUid' => 'exact', 'payedForUserUid' => 'exact'])]
†

2023-07-31 20:01 UTC, QoreCode commented on src/Filter/EntityFilter.php
> +        $this->identifiersExtractor = $identifiersExtractor;
†

2023-08-01 12:21 UTC, closed without merging